// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbv-gtm-9Z5_6Xb-91dn2URSOp8agTJ-U',
    appId: '1:142570199755:android:2f98fafb0e9aa933ea194e',
    messagingSenderId: '142570199755',
    projectId: 'e-commerce-334f2',
    storageBucket: 'e-commerce-334f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT6seDfPL1JTEcscMQTyDr3BbmLViVU-I',
    appId: '1:142570199755:ios:0f8a3bd9c10dd0dcea194e',
    messagingSenderId: '142570199755',
    projectId: 'e-commerce-334f2',
    storageBucket: 'e-commerce-334f2.firebasestorage.app',
    androidClientId:
        '42570199755-kppslon2cq1nsi6hah6bca4lchhn0ifs.apps.googleusercontent.com',
    iosClientId:
        '42570199755-kppslon2cq1nsi6hah6bca4lchhn0ifs.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
